# spring configuration
spring:
   application:
      name: emaillist
   
   # devtools - live reload
   devtools:
      livereload:
         enabled: true
            
   #mvc
   mvc:
      # Path pattern used for static resources
      static-path-pattern: /assets/**
      # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
      throw-exception-if-no-handler-found: true
   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/assets/
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false
      
  
   #datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.143:3307/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: utf-8
         enabled: true    
         
# logging
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: /${spring.application.name}-logs/exception.%d{yyyy-MM-dd}.%i.log.zip
         max-file-size: 200MB
         max-history: 10 
   file: 
       name: /${spring.application.name}-logs/exception.log
   level:
      root: INFO
      com:
         poscodx:
            emaillist:
               exception: ERROR      